FROM scylladb/scylla:2025.1

COPY wrapper.sh /usr/local/bin/wrapper.sh
#COPY scylla.5.4-experimental.yaml /etc/scylla/scylla.yaml

RUN chmod +x /usr/local/bin/wrapper.sh

ENTRYPOINT ["/usr/local/bin/wrapper.sh"]

CMD ["scylladb"]

HEALTHCHECK CMD cqlsh -e "SHOW VERSION" || exit 1
