FROM scylladb/scylla:2025.1

# For 'envsubst'
RUN apt-get -y clean expire-cache
RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get -y install gettext
# RUN microdnf --setopt=tsflags=nodocs -y install gettext-envsubst

COPY wrapper.sh /usr/local/bin/wrapper.sh
COPY scylla.yaml /etc/scylla/scylla.template.yaml

RUN chmod +x /usr/local/bin/wrapper.sh

ENTRYPOINT ["/usr/local/bin/wrapper.sh"]

CMD ["scylladb"]

HEALTHCHECK CMD cqlsh -e "SHOW VERSION" || exit 1
