FROM scylladb/scylla:2025.2

# For 'envsubst'
USER root
RUN microdnf clean all
RUN microdnf --setopt=tsflags=nodocs -y update
RUN microdnf --setopt=tsflags=nodocs -y install gettext
RUN microdnf clean all
COPY wrapper.sh /usr/local/bin/wrapper.sh
RUN chmod +x /usr/local/bin/wrapper.sh
RUN chown -R scylla:scylla /etc/scylla
USER scylla

COPY scylla.yaml /etc/scylla/scylla.template.yaml

ENTRYPOINT ["/usr/local/bin/wrapper.sh"]

CMD ["scylladb"]

HEALTHCHECK CMD cqlsh -e "SHOW VERSION" || exit 1
