# We use 5.1.4 specifically because newer version have broken IPv6 support
# REF: https://github.com/scylladb/scylladb/issues/14738
FROM scylladb/scylla:5.1.4

# For 'envsubst'
RUN dnf -y install gettext-envsubst

COPY wrapper.sh /usr/local/bin/wrapper.sh
COPY scylla.yaml /etc/scylla/scylla.template.yaml

RUN chmod +x /usr/local/bin/wrapper.sh

ENTRYPOINT ["/usr/local/bin/wrapper.sh"]

CMD ["scylladb"]

HEALTHCHECK CMD cqlsh -e "SHOW VERSION" || exit 1
